### PR TITLE
Add several new font images

### PR DESCRIPTION
**Pull request by nathanchapman**

### CODE REVIEW

**Comment by kern** [comment]
Awesome, thanks Nathan! :)

**Comment by nathanchapman** [comment]
I'd love to work with you on the colors too! Maybe we can use hex values from the material palette?
https://www.materialpalette.com/
Or pull random HD wallpapers from a repo?

**Comment by kern** [comment]
that sounds awesome, perhaps we could have a setting to toggle between the two?

**Comment by nathanchapman** [comment]
Sounds great!
I have a nice collection of HD wallpapers I can include, but that would greatly increase the size of the app..

**Comment by kern** [comment]
Perhaps you can pull images from unsplash.com?

**Pull request merged**
